// Survivors' Plot - lo-fi game-music runs on Suno's Simple tab.
// The prompt lives in docs/survivors-plot-prompt.txt; each create fills its INPUTS block.
// Shared queue: queue.html?q=sjm9xyp5 ("Survivors' Plot · lo-fi").
// verdict: '' (unheard) | 'keep' | 'maybe' | 'cut'  - filled in by ear, later.
const SP_QUEUE = 'sjm9xyp5';
const SP_PROMPT = 'v6';
const SP_CREATES = [
  { n: 1, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'low', setting: 'campfire inside the walls at dusk', weather: 'light rain', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '4cf1c26f-339c-4350-b059-b06f39a7de26', title: 'Okay for Now' }, { id: '81f76f59-69bb-439c-b99a-90309fcfd85b', title: 'Dusk Inside the Walls' } ] },
  { n: 2, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'hopeful', energy: 'steady', setting: 'morning chores in the rooftop garden', weather: 'clear, birdsong', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '13d1382d-ae8e-4fca-bb80-f44ad139bb28', title: 'Safe for Another Day' }, { id: '5b8c682a-9b01-4d83-951f-a87c065491df', title: 'Quietly Okay for Now' } ] },
  { n: 3, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'wistful', energy: 'low', setting: 'night watch on the wall, flashlight off', weather: 'cold wind', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'df758a55-363f-4271-b940-907ac66a6c10', title: 'Watch Still Keeping Time' }, { id: '1496ca60-e8d1-47ce-8969-fbd622a3bda9', title: 'Watch Still Keeping Time' } ] },
  { n: 4, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'busy', setting: 'workshop, sawdust and a radio', weather: 'overcast', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '731a6405-4424-4ba0-9d62-4a4be9dafe11', title: 'Safe for Now' }, { id: '6b4ff184-291c-4a9c-ab11-acd57174942f', title: 'Cozy Survival Workshop' } ] },
  { n: 5, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'low', setting: 'reading by lantern in the bunk room', weather: 'thunderstorm outside', threat: 'none', loop: 'yes', len: '3:00' },
    clips: [ { id: 'f4ae51dd-6be3-4dd2-bb05-d6bfb3ed77c8', title: 'At Ease Inside the Bunk Room' }, { id: '26e1c910-8047-431e-bf85-448e86b61882', title: 'Safe For Now' } ] },
  { n: 6, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'hopeful', energy: 'steady', setting: 'a trading caravan rolling up to the gate', weather: 'warm afternoon', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '91c8680d-92a4-46c2-875e-0c5e2c9bfd8a', title: 'Afternoon Caravan' }, { id: '558d6bd2-212f-45a2-a26f-1592b7b590e4', title: 'Afternoon Caravan' } ] },
  { n: 7, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'uneasy', energy: 'low', setting: 'boarding up the windows before nightfall', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
    clips: [ { id: '2ca0802e-311b-45df-aad8-5b370913010d', title: 'Safe For Now' }, { id: '69195a01-41f3-4527-936c-f55c8b6f13ec', title: 'Safe For Now' } ] },
  { n: 8, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'hauling salvage into piles; the music keeps a sorting rhythm, a little bittersweet', setting: 'sorting salvage from the old town', mood: 'wistful', energy: 'steady', weather: 'drizzle', threat: 'distant', loop: 'yes', len: '2:30' },
    clips: [ { id: '99a380c7-9da1-430b-a426-c3b40d4ab5f0', title: 'Salvage Sorting' }, { id: '5ac28c64-1c07-4525-975d-06e4930575f5', title: 'Salvage Sorting' } ] },
  { n: 9, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'cooking for everyone; says the camp is a family now', setting: 'the camp kitchen, stew on the stove', mood: 'cozy', energy: 'steady', weather: 'first snow', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: 'fe7d36e4-a86d-47ce-8643-d3192f273c8a', title: 'First Snowfall Stew' }, { id: '3ea5d46c-8e6e-45ef-a82f-248f1efd9be1', title: 'Stew and Snow' } ] },
  { n: 10, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'alone at the radio, scanning; says someone might be out there', setting: 'radio tower at night', mood: 'lonely', energy: 'low', weather: 'clear night, stars', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'f092260e-5d70-46f6-9849-07423809c03f', title: 'Clear-Night Watch' }, { id: 'bd5143b5-9f7d-4019-86da-fe614d952faf', title: 'Tape Start' } ] },
  { n: 11, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'fog swallows the fence line at 3am; something is out there, stay calm', setting: 'the fence line in thick fog', mood: 'eerie', energy: 'low', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
    clips: [ { id: 'f76fb237-c9c6-4db5-99e0-e632795cbdf9', title: 'Watch at the Fence' }, { id: '66353a88-1080-43e3-9b0e-ddf385da4253', title: 'Fence Wire in the Fog' } ] },
  { n: 12, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'a numbers station on the radio; who is broadcasting?', setting: 'the radio shack, a signal nobody sent', mood: 'mysterious', energy: 'low', weather: 'static-dry night', threat: 'distant', loop: 'yes', len: '2:30' },
    clips: [ { id: '8d7b78b3-439d-4c9f-9ec0-432c0107b928', title: 'Shortwave Bell' }, { id: 'b6cb5ace-acc2-444a-a1ba-739dbecfc8fe', title: 'Unsent Signal' } ] },
  { n: 13, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'the expedition leaves at dawn; the map ends here', setting: 'the open road past the last town', mood: 'adventurous', energy: 'busy', weather: 'cool clear morning', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: 'dafa5b2f-c4e0-4aec-baa3-620ba01a7e5d', title: 'Beyond the Last Town' }, { id: '868c4feb-f61c-474b-80b8-5100185911c9', title: 'Leaving the Last Town' } ] },
  { n: 14, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'picking the first crops; proud, the work paid off', setting: 'the vegetable beds on harvest day', mood: 'hopeful', energy: 'busy', weather: 'sunny', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '511a27e6-ca86-479e-ae0e-87e42d4a7736', title: 'Harvest Day Hum' }, { id: '8b7ded13-1648-4de7-862b-8f1e5e87a026', title: 'Harvest Day Garden' } ] },
  { n: 15, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'searching a dark ward by flashlight, slow and careful', setting: 'an abandoned hospital', mood: 'eerie', energy: 'low', weather: 'wind through broken windows', threat: 'near', loop: 'yes', len: '3:00' },
    clips: [ { id: '66374afd-fedb-438d-9d8e-cfcf61497260', title: 'Empty Ward' }, { id: '29e69f1d-c20f-4e4a-b3db-395da2975f29', title: 'Checking Each Doorway' } ] },
  { n: 16, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'the horde has passed and everyone sleeps; the music exhales', setting: 'the bunkhouse after a long night', mood: 'relieved', energy: 'low', weather: 'rain easing off', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'e4c6f252-2ca1-4a44-ba6f-3578c2966ef5', title: 'Pastoral Wander' }, { id: 'd32bc366-3c16-4c10-8537-55f9f032e5af', title: 'Morning Can Wait' } ] },
  { n: 17, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'a sealed bunker door with fresh footprints; what is inside?', setting: 'a bunker hidden in the forest', mood: 'mysterious', energy: 'steady', weather: 'damp pine air', threat: 'distant', loop: 'yes', len: '2:30' },
    clips: [ { id: '68b43aae-d8b4-4c7e-8974-2f336662a496', title: 'Damp Pines, Sealed Door' }, { id: '0cfd20b2-029c-448c-8ef7-04113f4d1150', title: '森の隠所' } ] },
  { n: 18, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'cycling the convoy through empty farmland; wind and open sky', setting: 'bicycle convoy through farm country', mood: 'adventurous', energy: 'busy', weather: 'sunny, breezy', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '9ba99ad6-b997-4579-9d63-06b5ff3c4228', title: 'Sunny Farmland Ride' }, { id: 'ed760ed5-22d4-4787-8cf9-4b137697c482', title: 'Convoy Home' } ] },
  { n: 19, date: '2026-09-27', prompt: 'v4',
    inputs: { moment: 'reading a found letter; a short sad memory, then it lets go', setting: 'an empty house in the old town', mood: 'wistful', energy: 'low', weather: 'overcast', threat: 'none', loop: 'no', len: '2:00' },
    clips: [ { id: '9211e979-ec6b-4eca-b606-dbfb36ce18bc', title: 'The Old Town Window' }, { id: '1fd6e85c-c3cb-475e-b72e-4aefb5784d46', title: 'The Old Town Window' } ] },
  { n: 20, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'lights moving in the woods at night; curious, not afraid', setting: 'the treeline past the orchard', mood: 'mysterious', energy: 'low', weather: 'clear night, crickets', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: '7497f1a4-9cef-4451-9e59-5cfc131faa93', title: 'Orchard Edge' }, { id: 'b142026f-72f7-4fe6-80ab-709e2a97f472', title: 'Treeline Past the Orchard' } ] },
  { n: 21, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'watching the sun set over the dead city; beautiful and sad', setting: 'the rooftop lookout', mood: 'wistful', energy: 'low', weather: 'golden haze', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: '4267a36b-89ae-4c66-a138-7eae35a8a18d', title: 'Rooftop in Golden Haze' }, { id: 'd3fdaeeb-3cae-4924-927e-e0c8f0b4e7f6', title: 'Rooftop Lookout' } ] },
  { n: 22, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'fishing off the old pier; nothing to do, and that is the point', setting: 'the river pier past the fence', mood: 'content', energy: 'low', weather: 'still, cicadas', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'e6dae80d-33a6-4a0f-a832-7af03b62c8df', title: 'Cicadas Over Still Water' }, { id: '9f62e2cd-5159-4384-826e-ebda74174396', title: 'Cicadas Over Still Water' } ] },
  { n: 23, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'wading the flooded subway; every drip echoes', setting: 'a flooded subway tunnel', mood: 'eerie', energy: 'low', weather: 'dripping, cold', threat: 'near', loop: 'yes', len: '2:30' },
    clips: [ { id: '23d4cdf2-c78b-48c6-ae42-1e366284e798', title: 'Flooded Passage' }, { id: '57ef001d-e94a-4555-b36b-a1c7201e95a2', title: 'Cold Tunnel Air' } ] },
  { n: 24, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'crossing the collapsed bridge one plank at a time', setting: 'a broken highway bridge over the river', mood: 'adventurous', energy: 'steady', weather: 'river wind', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'ecc4c0fb-e870-4595-886c-8f81848a90e5', title: 'Rusting Spans at Dawn' }, { id: 'ffac5e4f-eb2e-4df6-beb5-1149016fe3a9', title: 'The Far Bank' } ] },
  { n: 25, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'first sight of another settlement on the horizon', setting: 'a hilltop above an unknown town', mood: 'adventurous', energy: 'steady', weather: 'golden afternoon', threat: 'none', loop: 'yes', len: '3:00' },
    clips: [ { id: 'f3742227-8580-436a-9292-fb73835f3cd1', title: 'Golden Afternoon Hills' }, { id: 'a25d0a14-a984-4338-86f2-e6e1b951a8df', title: 'Hilltop Above an Unknown Town' } ] },
  { n: 26, date: '2026-09-27', prompt: 'v5',
    inputs: { moment: 'looting a pharmacy, ears open; focused, not scared', setting: 'scavenging run far from home', mood: 'uneasy', energy: 'steady', weather: 'gusting wind', threat: 'near', loop: 'yes', len: '3:00' },
    clips: [ { id: '46c4d43e-f847-4aeb-87af-cc2e1aefc0c5', title: 'Pharmacy Aisle' }, { id: '3387a4ba-7739-4d14-b294-f5b1188a7b78', title: 'Scavenging Run' } ] },
  { n: 27, date: '2026-09-27', prompt: 'v6',
    inputs: { moment: 'alone in the dark; something shifts just out of sight, hold your breath', setting: 'a fog-drowned dead suburb at 3am', mood: 'eerie, uncanny, dread', energy: 'low', weather: 'thick fog, dead still', threat: 'near', loop: 'yes', len: '3:00' },
    clips: [ { id: '4b1a0799-969b-4970-a0b7-5404152b2add', title: '3am Suburb' }, { id: '74aa5bd3-d4f6-4c64-94e1-fd725fa190d0', title: 'Fog-Muted Neighborhood' } ] },
  { n: 28, date: '2026-09-27', prompt: 'v6-dread',
    // one-off: v6 with "spacious and warm" -> "cold", "Eerie and mysterious stay soft and listenable." -> "Ominous means full dread: sub-bass drones, dissonant clusters, a slow funeral pulse closing in.", adventurous clause dropped for room
    inputs: { moment: 'the horde found the base; death is coming', setting: 'the last barricade at midnight', mood: 'ominous, creepy, doom', energy: 'low', weather: 'blood moon, no wind', threat: 'near', loop: 'yes', len: '3:00' },
    clips: [] },
];
// What each prompt version changed, and why.
const SP_VERSIONS = [
  { v: 'v1', date: '2026-09-27', note: 'Classical modular brief rewritten as lo-fi beat tape: seven inputs, beat-tape section names, loop-safe ending.' },
  { v: 'v2', date: '2026-09-27', note: 'v1 made every scene one song: all 14 takes at 76-78 BPM on Rhodes + music box, the Setting only added quiet foley, and "okay, for now" in the brief titled 4 of 7 takes Safe For Now. v2 adds a Game moment input and a think-about-the-setting step that picks the lead instrument, ties BPM to Energy, caps length under 4:00, and bans safe/okay/survive in titles.' },
  { v: 'v3', date: '2026-09-27', note: 'BlazeDale asked for eerie, mysterious and adventurous cues too. Mood rules gained eerie (detuned, whole-tone/diminished, reversed tape, long gaps), mysterious (dorian/phrygian, unresolved) and adventurous (lydian/mixolydian, forward pulse, climbing motif); eerie and mysterious stay lo-fi, never horror. Wording trimmed to keep room under the 3,000 cap.' },
  { v: 'v4', date: '2026-09-27', note: 'BlazeDale: the tracks are good but too jazzy for the game; wants cozy anime-game. Genre changed from lo-fi hip-hop to a cozy anime-game soundtrack (hand-drawn slice-of-life village theme, hummable acoustic melody). Harmony now plain diatonic triads/add2/sus2 instead of 7ths and 9ths; straight eighths or 3/4 or 6/8 instead of lazy swing; acoustic base (piano, nylon guitar, light strings, glockenspiel, hand percussion); tempo bands raised; sections renamed Intro / Theme A / Theme B / Interlude / Theme A Return / Breakdown / Loop Point. Steered positively only: jazz markers are left unnamed rather than excluded.' },
  { v: 'v5', date: '2026-09-27', note: 'BlazeDale: needs more ambient, atmospheric tunes. v4 anime-game kept its warmth but became exploration ambience: a pad/drone bed plus a floating voice (felt piano, celesta, bells, ocarina, harp), a 3-5 note fragment drifting in and out with long silences, 60-76 BPM or free time, long reverb, chords changing every few bars, no percussion (energy now sets pulse: none / soft arpeggio / rippling ostinato), place sounds woven into the texture. Sections: Opening / Drift A / Drift B / Swell / Clearing / Drift A Return / Loop Point.' },
  { v: 'v6', date: '2026-09-27', note: 'Flooded Passage had sung notes. Its lyric field had bracketed headers but bare description lines, and Suno sings bare text. Takes with bare lines by version: v1 0/14, v2 4/6, v3 4/6, v4 6/12, v5 13/14. Cause: my trims. v2 dropped "bracketed" from the per-section line ("2-4 lines" instead of "2-4 bracketed lines"), which the model follows over the general rule; v3 cut "No unbracketed text". v5 also said "choir-like synth" and "the voice that floats over it". v6 puts every line in brackets explicitly (headers and descriptions, "any bare text gets sung"), restores "bracketed" in the per-section line with a two-line example, and removes choir/voice.' },
];

// Scene deck for the rolling queue: the next unused scene is fired, top down. Add freely.
// moment = what the player is doing and what the music must tell them. Keep it under ~100 chars (Simple box caps at 3,000).
const SP_SCENES = [
  { moment: 'hauling salvage into piles; the music keeps a sorting rhythm, a little bittersweet', setting: 'sorting salvage from the old town', mood: 'wistful', energy: 'steady', weather: 'drizzle', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'cooking for everyone; says the camp is a family now', setting: 'the camp kitchen, stew on the stove', mood: 'cozy', energy: 'steady', weather: 'first snow', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'alone at the radio, scanning; says someone might be out there', setting: 'radio tower at night', mood: 'lonely', energy: 'low', weather: 'clear night, stars', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'fog swallows the fence line at 3am; something is out there, stay calm', setting: 'the fence line in thick fog', mood: 'eerie', energy: 'low', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'a numbers station on the radio; who is broadcasting?', setting: 'the radio shack, a signal nobody sent', mood: 'mysterious', energy: 'low', weather: 'static-dry night', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'picking the first crops; proud, the work paid off', setting: 'the vegetable beds on harvest day', mood: 'hopeful', energy: 'busy', weather: 'sunny', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'the expedition leaves at dawn; the map ends here', setting: 'the open road past the last town', mood: 'adventurous', energy: 'busy', weather: 'cool clear morning', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'searching a dark ward by flashlight, slow and careful', setting: 'an abandoned hospital', mood: 'eerie', energy: 'low', weather: 'wind through broken windows', threat: 'near', loop: 'yes', len: '3:00' },
  { moment: 'the horde has passed and everyone sleeps; the music exhales', setting: 'the bunkhouse after a long night', mood: 'relieved', energy: 'low', weather: 'rain easing off', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'a sealed bunker door with fresh footprints; what is inside?', setting: 'a bunker hidden in the forest', mood: 'mysterious', energy: 'steady', weather: 'damp pine air', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'cycling the convoy through empty farmland; wind and open sky', setting: 'bicycle convoy through farm country', mood: 'adventurous', energy: 'busy', weather: 'sunny, breezy', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'reading a found letter; a short sad memory, then it lets go', setting: 'an empty house in the old town', mood: 'wistful', energy: 'low', weather: 'overcast', threat: 'none', loop: 'no', len: '2:00' },
  { moment: 'a music box plays by itself in an empty house', setting: 'a bedroom in a dead suburb', mood: 'eerie', energy: 'low', weather: 'dusk, still', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'lights moving in the woods at night; curious, not afraid', setting: 'the treeline past the orchard', mood: 'mysterious', energy: 'low', weather: 'clear night, crickets', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'tinkering until it sputters to life; fiddly, patient, satisfying', setting: 'the generator shed, grease and a toolbox', mood: 'content', energy: 'steady', weather: 'humid summer', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'crossing the collapsed bridge one plank at a time', setting: 'a broken highway bridge over the river', mood: 'adventurous', energy: 'steady', weather: 'river wind', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'wading the flooded subway; every drip echoes', setting: 'a flooded subway tunnel', mood: 'eerie', energy: 'low', weather: 'dripping, cold', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'title screen; welcome home, press start', setting: 'main menu: the base at dawn', mood: 'hopeful', energy: 'low', weather: 'mist lifting', threat: 'none', loop: 'yes', len: '2:00' },
  { moment: 'decoding a map found on a stranger', setting: 'the map table by candlelight', mood: 'mysterious', energy: 'steady', weather: 'rain on the roof', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'first sight of another settlement on the horizon', setting: 'a hilltop above an unknown town', mood: 'adventurous', energy: 'steady', weather: 'golden afternoon', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'looting a pharmacy, ears open; focused, not scared', setting: 'scavenging run far from home', mood: 'uneasy', energy: 'steady', weather: 'gusting wind', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'morning rounds with the animals; gentle routine', setting: 'the chicken coop and the camp dog', mood: 'cozy', energy: 'low', weather: 'crisp autumn morning', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'raising a new wall section together; teamwork, hammers in time', setting: 'the east wall construction site', mood: 'content', energy: 'busy', weather: 'bright and breezy', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'watching the sun set over the dead city; beautiful and sad', setting: 'the rooftop lookout', mood: 'wistful', energy: 'low', weather: 'golden haze', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'mending clothes while the storm howls; snug and small', setting: 'by the wood stove', mood: 'cozy', energy: 'low', weather: 'blizzard', threat: 'none', loop: 'yes', len: '3:00' },
  { moment: 'haggling at the gate; playful, a bit of swagger', setting: 'the trading post counter', mood: 'hopeful', energy: 'steady', weather: 'warm afternoon', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'fishing off the old pier; nothing to do, and that is the point', setting: 'the river pier past the fence', mood: 'content', energy: 'low', weather: 'still, cicadas', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'teaching a newcomer to build; warm, a little funny', setting: 'the carpentry bench', mood: 'cozy', energy: 'steady', weather: 'overcast', threat: 'none', loop: 'yes', len: '2:30' },
];
