// Survivors' Plot - lo-fi game-music runs on Suno's Simple tab.
// The prompt lives in docs/survivors-plot-prompt.txt; each create fills its INPUTS block.
// Shared queue: queue.html?q=sjm9xyp5 ("Survivors' Plot · lo-fi").
// verdict: '' (unheard) | 'keep' | 'maybe' | 'cut'  - filled in by ear, later.
const SP_QUEUE = 'sjm9xyp5';
const SP_PROMPT = 'v4';
const SP_CREATES = [
  { n: 1, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'low', setting: 'campfire inside the walls at dusk', weather: 'light rain', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '4cf1c26f-339c-4350-b059-b06f39a7de26', title: 'Okay for Now' }, { id: '81f76f59-69bb-439c-b99a-90309fcfd85b', title: 'Dusk Inside the Walls' } ] },
  { n: 2, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'hopeful', energy: 'steady', setting: 'morning chores in the rooftop garden', weather: 'clear, birdsong', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '13d1382d-ae8e-4fca-bb80-f44ad139bb28', title: 'Safe for Another Day' }, { id: '5b8c682a-9b01-4d83-951f-a87c065491df', title: 'Quietly Okay for Now' } ] },
  { n: 3, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'wistful', energy: 'low', setting: 'night watch on the wall, flashlight off', weather: 'cold wind', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'df758a55-363f-4271-b940-907ac66a6c10', title: 'Watch Still Keeping Time' }, { id: '1496ca60-e8d1-47ce-8969-fbd622a3bda9', title: 'Watch Still Keeping Time' } ] },
  { n: 4, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'busy', setting: 'workshop, sawdust and a radio', weather: 'overcast', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '731a6405-4424-4ba0-9d62-4a4be9dafe11', title: 'Safe for Now' }, { id: '6b4ff184-291c-4a9c-ab11-acd57174942f', title: 'Cozy Survival Workshop' } ] },
  { n: 5, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'cozy', energy: 'low', setting: 'reading by lantern in the bunk room', weather: 'thunderstorm outside', threat: 'none', loop: 'yes', len: '3:00' },
    clips: [ { id: 'f4ae51dd-6be3-4dd2-bb05-d6bfb3ed77c8', title: 'At Ease Inside the Bunk Room' }, { id: '26e1c910-8047-431e-bf85-448e86b61882', title: 'Safe For Now' } ] },
  { n: 6, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'hopeful', energy: 'steady', setting: 'a trading caravan rolling up to the gate', weather: 'warm afternoon', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: '91c8680d-92a4-46c2-875e-0c5e2c9bfd8a', title: 'Afternoon Caravan' }, { id: '558d6bd2-212f-45a2-a26f-1592b7b590e4', title: 'Afternoon Caravan' } ] },
  { n: 7, date: '2026-09-27', prompt: 'v1',
    inputs: { mood: 'uneasy', energy: 'low', setting: 'boarding up the windows before nightfall', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
    clips: [ { id: '2ca0802e-311b-45df-aad8-5b370913010d', title: 'Safe For Now' }, { id: '69195a01-41f3-4527-936c-f55c8b6f13ec', title: 'Safe For Now' } ] },
  { n: 8, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'hauling salvage into piles; the music keeps a sorting rhythm, a little bittersweet', setting: 'sorting salvage from the old town', mood: 'wistful', energy: 'steady', weather: 'drizzle', threat: 'distant', loop: 'yes', len: '2:30' },
    clips: [ { id: '99a380c7-9da1-430b-a426-c3b40d4ab5f0', title: 'Salvage Sorting' }, { id: '5ac28c64-1c07-4525-975d-06e4930575f5', title: 'Salvage Sorting' } ] },
  { n: 9, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'cooking for everyone; says the camp is a family now', setting: 'the camp kitchen, stew on the stove', mood: 'cozy', energy: 'steady', weather: 'first snow', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [ { id: 'fe7d36e4-a86d-47ce-8643-d3192f273c8a', title: 'First Snowfall Stew' }, { id: '3ea5d46c-8e6e-45ef-a82f-248f1efd9be1', title: 'Stew and Snow' } ] },
  { n: 10, date: '2026-09-27', prompt: 'v2',
    inputs: { moment: 'alone at the radio, scanning; says someone might be out there', setting: 'radio tower at night', mood: 'lonely', energy: 'low', weather: 'clear night, stars', threat: 'distant', loop: 'yes', len: '3:00' },
    clips: [ { id: 'f092260e-5d70-46f6-9849-07423809c03f', title: 'Clear-Night Watch' }, { id: 'bd5143b5-9f7d-4019-86da-fe614d952faf', title: 'Tape Start' } ] },
  { n: 11, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'fog swallows the fence line at 3am; something is out there, stay calm', setting: 'the fence line in thick fog', mood: 'eerie', energy: 'low', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
    clips: [] },
  { n: 12, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'a numbers station on the radio; who is broadcasting?', setting: 'the radio shack, a signal nobody sent', mood: 'mysterious', energy: 'low', weather: 'static-dry night', threat: 'distant', loop: 'yes', len: '2:30' },
    clips: [] },
  { n: 13, date: '2026-09-27', prompt: 'v3',
    inputs: { moment: 'the expedition leaves at dawn; the map ends here', setting: 'the open road past the last town', mood: 'adventurous', energy: 'busy', weather: 'cool clear morning', threat: 'none', loop: 'yes', len: '2:30' },
    clips: [] },
];
// What each prompt version changed, and why.
const SP_VERSIONS = [
  { v: 'v1', date: '2026-09-27', note: 'Classical modular brief rewritten as lo-fi beat tape: seven inputs, beat-tape section names, loop-safe ending.' },
  { v: 'v2', date: '2026-09-27', note: 'v1 made every scene one song: all 14 takes at 76-78 BPM on Rhodes + music box, the Setting only added quiet foley, and "okay, for now" in the brief titled 4 of 7 takes Safe For Now. v2 adds a Game moment input and a think-about-the-setting step that picks the lead instrument, ties BPM to Energy, caps length under 4:00, and bans safe/okay/survive in titles.' },
  { v: 'v3', date: '2026-09-27', note: 'BlazeDale asked for eerie, mysterious and adventurous cues too. Mood rules gained eerie (detuned, whole-tone/diminished, reversed tape, long gaps), mysterious (dorian/phrygian, unresolved) and adventurous (lydian/mixolydian, forward pulse, climbing motif); eerie and mysterious stay lo-fi, never horror. Wording trimmed to keep room under the 3,000 cap.' },
  { v: 'v4', date: '2026-09-27', note: 'BlazeDale: the tracks are good but too jazzy for the game; wants cozy anime-game. Genre changed from lo-fi hip-hop to a cozy anime-game soundtrack (hand-drawn slice-of-life village theme, hummable acoustic melody). Harmony now plain diatonic triads/add2/sus2 instead of 7ths and 9ths; straight eighths or 3/4 or 6/8 instead of lazy swing; acoustic base (piano, nylon guitar, light strings, glockenspiel, hand percussion); tempo bands raised; sections renamed Intro / Theme A / Theme B / Interlude / Theme A Return / Breakdown / Loop Point. Steered positively only: jazz markers are left unnamed rather than excluded.' },
];

// Scene deck for the rolling queue: the next unused scene is fired, top down. Add freely.
// moment = what the player is doing and what the music must tell them. Keep it under ~100 chars (Simple box caps at 3,000).
const SP_SCENES = [
  { moment: 'hauling salvage into piles; the music keeps a sorting rhythm, a little bittersweet', setting: 'sorting salvage from the old town', mood: 'wistful', energy: 'steady', weather: 'drizzle', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'cooking for everyone; says the camp is a family now', setting: 'the camp kitchen, stew on the stove', mood: 'cozy', energy: 'steady', weather: 'first snow', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'alone at the radio, scanning; says someone might be out there', setting: 'radio tower at night', mood: 'lonely', energy: 'low', weather: 'clear night, stars', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'fog swallows the fence line at 3am; something is out there, stay calm', setting: 'the fence line in thick fog', mood: 'eerie', energy: 'low', weather: 'fog', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'a numbers station on the radio; who is broadcasting?', setting: 'the radio shack, a signal nobody sent', mood: 'mysterious', energy: 'low', weather: 'static-dry night', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'picking the first crops; proud, the work paid off', setting: 'the vegetable beds on harvest day', mood: 'hopeful', energy: 'busy', weather: 'sunny', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'the expedition leaves at dawn; the map ends here', setting: 'the open road past the last town', mood: 'adventurous', energy: 'busy', weather: 'cool clear morning', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'searching a dark ward by flashlight, slow and careful', setting: 'an abandoned hospital', mood: 'eerie', energy: 'low', weather: 'wind through broken windows', threat: 'near', loop: 'yes', len: '3:00' },
  { moment: 'the horde has passed and everyone sleeps; the music exhales', setting: 'the bunkhouse after a long night', mood: 'relieved', energy: 'low', weather: 'rain easing off', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'a sealed bunker door with fresh footprints; what is inside?', setting: 'a bunker hidden in the forest', mood: 'mysterious', energy: 'steady', weather: 'damp pine air', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'cycling the convoy through empty farmland; wind and open sky', setting: 'bicycle convoy through farm country', mood: 'adventurous', energy: 'busy', weather: 'sunny, breezy', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'reading a found letter; a short sad memory, then it lets go', setting: 'an empty house in the old town', mood: 'wistful', energy: 'low', weather: 'overcast', threat: 'none', loop: 'no', len: '2:00' },
  { moment: 'a music box plays by itself in an empty house', setting: 'a bedroom in a dead suburb', mood: 'eerie', energy: 'low', weather: 'dusk, still', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'lights moving in the woods at night; curious, not afraid', setting: 'the treeline past the orchard', mood: 'mysterious', energy: 'low', weather: 'clear night, crickets', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'tinkering until it sputters to life; fiddly, patient, satisfying', setting: 'the generator shed, grease and a toolbox', mood: 'content', energy: 'steady', weather: 'humid summer', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'crossing the collapsed bridge one plank at a time', setting: 'a broken highway bridge over the river', mood: 'adventurous', energy: 'steady', weather: 'river wind', threat: 'distant', loop: 'yes', len: '2:30' },
  { moment: 'wading the flooded subway; every drip echoes', setting: 'a flooded subway tunnel', mood: 'eerie', energy: 'low', weather: 'dripping, cold', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'title screen; welcome home, press start', setting: 'main menu: the base at dawn', mood: 'hopeful', energy: 'low', weather: 'mist lifting', threat: 'none', loop: 'yes', len: '2:00' },
  { moment: 'decoding a map found on a stranger', setting: 'the map table by candlelight', mood: 'mysterious', energy: 'steady', weather: 'rain on the roof', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'first sight of another settlement on the horizon', setting: 'a hilltop above an unknown town', mood: 'adventurous', energy: 'steady', weather: 'golden afternoon', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'looting a pharmacy, ears open; focused, not scared', setting: 'scavenging run far from home', mood: 'uneasy', energy: 'steady', weather: 'gusting wind', threat: 'near', loop: 'yes', len: '2:30' },
  { moment: 'morning rounds with the animals; gentle routine', setting: 'the chicken coop and the camp dog', mood: 'cozy', energy: 'low', weather: 'crisp autumn morning', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'raising a new wall section together; teamwork, hammers in time', setting: 'the east wall construction site', mood: 'content', energy: 'busy', weather: 'bright and breezy', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'watching the sun set over the dead city; beautiful and sad', setting: 'the rooftop lookout', mood: 'wistful', energy: 'low', weather: 'golden haze', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'mending clothes while the storm howls; snug and small', setting: 'by the wood stove', mood: 'cozy', energy: 'low', weather: 'blizzard', threat: 'none', loop: 'yes', len: '3:00' },
  { moment: 'haggling at the gate; playful, a bit of swagger', setting: 'the trading post counter', mood: 'hopeful', energy: 'steady', weather: 'warm afternoon', threat: 'none', loop: 'yes', len: '2:30' },
  { moment: 'fishing off the old pier; nothing to do, and that is the point', setting: 'the river pier past the fence', mood: 'content', energy: 'low', weather: 'still, cicadas', threat: 'distant', loop: 'yes', len: '3:00' },
  { moment: 'teaching a newcomer to build; warm, a little funny', setting: 'the carpentry bench', mood: 'cozy', energy: 'steady', weather: 'overcast', threat: 'none', loop: 'yes', len: '2:30' },
];
